### ISSUE TITLE
Not requesting permission on macos Ventura

### ISSUE THREAD

**Issue by puf** [llfbandit/record#137]
**Package version**

In pubspec.yaml
  ```
  record: ^4.4.4
  ```
In pubspec.lock
  ```
  record_macos:
    dependency: transitive
    description:
      name: record_macos
      sha256: d1d0199d1395f05e218207e8cacd03eb9dc9e256ddfe2cfcbbb90e8edea06057
      url: "https://pub.dev"
    source: hosted
    version: "0.2.2"
  ```

**Describe the bug**

I'm trying to record audio on a macOS app. Calling `listInputDevices` returns 3 audio devices, but `hasPermission()` always returns false.

**To Reproduce**
```
final _audioRecorder = Record();
...
if (await _audioRecorder.hasPermission()) {
  if (_isRecording) {
    print('Stopping recording');
    var result = _audioRecorder.stop();
    print(result);
  }
  else {
    print('Starting recording');
    await _audioRecorder.start();
  }
}
else {
  print('No permission');
}
```

Output:

> flutter: No permission

If I skip the `hasPermission()` check, I get an exception:

> PlatformException(-2, Failed to start recording, Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use MacBook Pro Microphone" UserInfo={NSLocalizedFailureReason=This app is not authorized to use MacBook Pro Microphone., AVErrorDeviceKey=<AVCaptureHALDevice: 0x7fe034385100 [MacBook Pro Microphone][BuiltInMicrophoneDevice]>, NSLocalizedDescription=Cannot use MacBook Pro Microphone}, null)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Ventura - 13.2.1 (22D68)
