### ISSUE TITLE
[Question] Integration into existing app

### ISSUE THREAD

**Issue by scheung38** [llfbandit/record#23]
Why in the example main.dart when right clicked inside VSCode and Goto Definition:

import 'package:record/record.dart'

it is directed to:

![Screenshot 2021-07-21 at 19 42 08](https://user-images.githubusercontent.com/1273014/126542401-cbf2ce06-0c37-4705-860a-bbeeca1f1f04.png)

and clicked on

export 'package:record/src/record.dart';

takes us to:

![Screenshot 2021-07-21 at 19 43 07](https://user-images.githubusercontent.com/1273014/126542513-49623ace-1608-4935-a37c-8f913ae6d1d1.png)

But in my own local project doing the same clicking on 

import 'package:record/record.dart';

$HOME/.pub-cache/hosted/pub.dartlang.org/record-2.1.1/lib/record.dart

![Screenshot 2021-07-21 at 19 44 29](https://user-images.githubusercontent.com/1273014/126542717-59659268-ae6f-48c1-854e-4e41de6a7137.png)

Is this because my path_provider or something is not setup correctly as i expect both the example and in my local project to point to the same Record class. thanks.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  just_audio:
  path_provider: 
  
  record: 
    path: ../

**Comment by llfbandit** [comment]
This is because you're not comparing same package versions. Record latest version is 3. You're on 2.1.1 in your local project.

**Comment by scheung38** [comment]
@llfbandit thanks is my setup correct?

```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  algolia: ^0.1.4+3

  assets_audio_player: 
  auto_size_text:
  built_collection: ^5.0.0
  built_value: ^8.0.6
  cached_network_image:  
  cloud_firestore: 
  equatable: ^1.2.5
  firebase_auth:  
  firebase_core: 
  font_awesome_flutter:
  geolocator:
  google_fonts: ^1.1.2
  google_sign_in: ^4.0.16
  intl:
  json_path: ^0.2.1
  json_serializable: ^3.5.1
  page_transition:
  rxdart: 
  sign_in_with_apple: ^2.5.4
  timeago:
  url_launcher:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_native_splash: 

  just_audio:
  path_provider: 

  record_platform_interface: 

  record:
    path: ../ 

    



dev_dependencies:
  build_runner: ^1.11.5
  built_value_generator: ^8.0.4

  flutter_test:
    sdk: flutter


flutter_native_splash:
  color: "#b496d6"
  image: assets/images/snippets_800.png
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  plugin:
    platforms:
      android:
        package: com.llfbandit.record
        pluginClass: RecordPlugin
      ios:
        pluginClass: RecordPlugin
```

Didn't want to upgrade to 3 as a lot of the other packages are not yet null-safety, so this means until the others are migrated we wont be able to use 3?
