### ISSUE TITLE
[Question] Working with 2.1.1 with just_audio 

### ISSUE THREAD

**Issue by scheung38** [llfbandit/record#24]
Hi @llfbandit : flutter pub add record but with version 2.1.1

dependencies:
  record: ^2.1.1

import 'package:record/record.dart'; <--

Target of URI doesn't exist: 'package:record/record.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.

![Screenshot 2021-07-22 at 23 34 17](https://user-images.githubusercontent.com/1273014/126717683-dd44c893-3e80-44a0-a33b-cddf6c5f442c.png)

 
![Screenshot 2021-07-22 at 23 35 26](https://user-images.githubusercontent.com/1273014/126717755-64f1fe94-6647-47cb-9b10-76fad39dd6bd.png)

**Comment by scheung38** [comment]
@llfbandit Managed to not break existing project with version 2.1.1, however what is the 

flutter: MissingPluginException(No implementation found for method hasPermission on channel com.llfbandit.record)

upon using it:


```
children: <Widget>[
                                      AudioRecorder(
                                        path: null,
                                        onStop: () {
                                          setState(() => showPlayer = true);
                                        },
                                      ),
```
path was set to null as builder: (BuildContext context, snapshot) <--- 
![Screenshot 2021-07-23 at 22 29 18](https://user-images.githubusercontent.com/1273014/126843408-5ec7e8f2-b37b-4560-a142-27dda50be6b1.png)
                                      
                                      
Tried:

```
  plugin:        
    platforms:
      android:
        package: com.llfbandit.record
        pluginClass: MethodChannel # RecordPlugin
      ios:
        pluginClass: MethodChannel
      macos:
        pluginClass: MethodChannel
```
        
But made no difference
